### ISSUE TITLE
Occurences of /v/ that looks like it should maybe be /ɤ/

### ISSUE THREAD

**Issue by XachaB** [lexibank/suntb#9]
Hi,

In the language DaliBai, Erich noticed forms such as:

Form | Dataset  | ID
-- | -- | --
tɕ i ²¹ + tɕ ɑ ³⁵ + ts v ²¹ | suntb | DaliBai-166_earthworm-1
ɑ ³¹ + ŋ v ⁵³ | suntb | DaliBai-941_tenthousand-1
ɲ v ³³ + ȵ i ²¹ | suntb | DaliBai-291_woman-1
p i ³¹ + f v ⁴⁴ + ts i ⁴⁴ | suntb | DaliBai-240_nose-1

Where it happens that the dataset allenbai shows cognates with /ɤ/ rather than /v/:

Form  | Dataset  | ID 
-- | -- | --
p i ²¹ + tɕ a ³⁵ + ts ɤ ²¹ | allenbai | Qiliqiao-81_earthworm-1
a ³¹ + ŋ ɤ ³² | allenbai | Qiliqiao-462_tenthousand-1
ɲ ɤ ³³ + ɲ i ²¹ | allenbai | Zhoucheng-156_woman-1
p i ²¹ + f ɤ ⁴⁴ + ts ɿ ³³ | allenbai | Zhoucheng-128_nose-1

We suspect that /v/ in these forms in suntb might actually be /ɤ/.

**Comment by LinguList** [comment]
No, these are fricative vowels, or vowels with frication, such as a v 
that is vocalic. They occur in SEA languages, like Chinese, and Bai, and 
they often write them without the syllabicity marker, in CLTS we have a 
specific symbol they use in SEA languages.

**Comment by erichround** [comment]
I understand. Is there a reason to leave them as /v/, though, rather than standardising them to a rounded close with-frication central vowel /ʯ/ or rounded close with-frication back vowel /ʮ/? Leaving them as /v/ complicates automated comparison and can lead to users mis-classifying the segments unless they do data checks like we did ... which then may just lead to more github issues getting opened up, that you have to deal with.

**Comment by LinguList** [comment]
Of course. I did not make the original profile for this dataset. But you 
are right, it should be standardized, and I'll look into this along with 
thee other issues which I noted down, which you brought up!

**Comment by XachaB** [comment]
Thanks !
